Repository buildtesters/buildtest-nersc, pull requests merged in 2021-03, with the labels that each got.

#32 adding perlmutter system entry and adding first tests for perlmutter
  .buildtest/config.yml
  buildspecs/modules/ml_test.yml
  buildspecs/modules/module_sanity.yml
  buildspecs/modules/spider_check.yml
  buildspecs/modules/swap_modules.yml
Labels: size/L

#33 update executor in e4s tests
  buildspecs/e4s/adios2/e4s_adios2.yml
  buildspecs/e4s/bolt/e4s_bolt.yml
  buildspecs/e4s/caliper/e4s_caliper.yml
  buildspecs/e4s/flit/e4s_flit.yml
  buildspecs/e4s/gasnet/e4s_gasnet.yml
  buildspecs/e4s/ginkgo/e4s_ginkgo.yml
  buildspecs/e4s/hdf5/e4s_hdf5.yml
  buildspecs/e4s/hypre/e4s_hypre.yml
  buildspecs/e4s/kokkos/e4s_kokkos.yml
  buildspecs/e4s/libquo/e4s_libquo.yml
  buildspecs/e4s/mfem/e4s_mfem.yml
  buildspecs/e4s/ninja/e4s_ninja.yml
  buildspecs/e4s/papyrus/e4s_papyrus.yml
  buildspecs/e4s/qthreads/e4s_qthreads.yml
  buildspecs/e4s/raja/e4s_raja.yml
  buildspecs/e4s/slepc/e4s_slepc.yml
  buildspecs/e4s/strumpack/e4s_strumpack.yml
  buildspecs/e4s/sundials/e4s_sundials.yml
  buildspecs/e4s/superlu-dist/e4s_superlu-dist.yml
  buildspecs/e4s/superlu/e4s_superlu.yml
  buildspecs/e4s/tasmanian/e4s_tasmanian.yml
  buildspecs/e4s/umpire/e4s_umpire.yml
  buildspecs/e4s/upcxx/e4s_upcxx.yml
  buildspecs/e4s/veloc/e4s_veloc.yml
Labels: size/M

#35 forgot to add -y in creating conda environment
  .gitlab-ci.yml
Labels: size/XS

#36 add 'daily' tags for tests that will run on daily schedule
  .gitlab-ci.yml
  buildspecs/apps/bupc/hello-bupc.yml
  buildspecs/apps/upc/hello.yml
  buildspecs/basic_functionality/ssh_host_auth.yml
  buildspecs/basic_functionality/time_test.yml
  buildspecs/esslurm/check_admin_comment_esslurm.yml
  buildspecs/filesystem/cvmfs.yml
  buildspecs/filesystem/filesystem.yml
  buildspecs/filesystem/gpfs.yml
  buildspecs/filesystem/ls.yml
  buildspecs/filesystem/lustre.yml
  buildspecs/jobs/data_stage_burst_buffer.yml
  buildspecs/jobs/delete_buffer.yml
  buildspecs/jobs/fail/max_nodes_haswell.yml
  buildspecs/jobs/fail/max_nodes_knl.yml
  buildspecs/jobs/fail/oom.yml
  buildspecs/jobs/fail/submit_limit_test.yml
  buildspecs/jobs/fail/time_limit_queue.yml
  buildspecs/jobs/gpuquery.yml
  buildspecs/modules/module_version.yml
  buildspecs/queues/bigmem.yml
  buildspecs/queues/compile.yml
  buildspecs/queues/debug.yml
  buildspecs/queues/premium.yml
  buildspecs/queues/shared.yml
  buildspecs/queues/xfer.yml
  buildspecs/slurm/partition.yml
  buildspecs/slurm/sacct_large_query.yml
  buildspecs/slurm/sacctmgr.yml
  buildspecs/slurm/scontrol.yml
  buildspecs/slurm/sinfo.yml
  buildspecs/slurm/slurm_check.yml
  buildspecs/slurm/slurm_cluster.yml
  buildspecs/slurm/squeue.yml
  buildspecs/system/cray_env.yml
  buildspecs/system/etc_profile.d/alias.bash.yml
  buildspecs/system/etc_profile.d/clock.sh.yml
  buildspecs/system/etc_profile.d/zzz-uegdotfile.sh.yml
  buildspecs/system/kernel.yml
  buildspecs/system/mountpoint.yml
  buildspecs/system/nameserver.yml
  buildspecs/system/nerschost.yml
  buildspecs/system/os_release.yml
  buildspecs/system/ping_nodes.yml
  buildspecs/system/ssh_nodes.yml
  buildspecs/system/timezone.yml
  buildspecs/system/ulimits.yml
  buildspecs/tools/iris.yml
  buildspecs/tools/myquota.yml
  buildspecs/tools/sqs.yml
Labels: size/L

#40 add CDASH script for importing buildtest test results
  .gitlab-ci.yml
  buildspecs/esslurm/check_admin_comment_esslurm.yml
  buildtest_cdash.py
Labels: size/L

#41 Report more information to CDash
  buildtest_cdash.py
Labels: size/S

#42 add upc pi test
  buildspecs/apps/upc/pi.yml
  buildspecs/apps/upc/src/pi.c
Labels: size/M
