Repository buildtesters/buildtest-nersc, pull requests merged in 2021-04, with the labels that each got.

#43 update cdash script with more fields
  buildtest_cdash.py
Labels: size/M

#44 Report labels and preformatted fields to CDash
  buildtest_cdash.py
Labels: size/M

#45 remove buildtest_cdash.py script in replacement for buildtest cdash upload command
  .gitlab-ci.yml
  README.md
  buildtest_cdash.py
  config.yml
Labels: size/L

#46 invalid configuration in cdash section
  config.yml
Labels: size/XS

#47 update README and remove manual trigger
  .gitlab-ci.yml
  README.md
Labels: size/L

#49 Update hybrid-hello.yml
  buildspecs/apps/mpi/hybrid-hello.yml
Labels: size/XS
