Repository buildtesters/buildtest-nersc, pull requests merged in 2023-12, with the labels that each got.

#236 add spack dependency check test from NERSC Spack Infrastructure
  buildspecs/apps/spack/spack_dep_check.yml
Labels: size/S

#238 rewrite kokkos test using e4s/23.05 stack
  buildspecs/apps/kokkos/e4s-22.05-kokkos_axpby.yml
  buildspecs/apps/kokkos/e4s-23.05-kokkos-cuda.sh
  buildspecs/apps/kokkos/e4s-23.05-kokkos-openmp.sh
  buildspecs/apps/kokkos/e4s-23.05-kokkos_axpby.yml
Labels: size/M

#239 add apps large tests in gitlab CI
  .gitlab-ci.yml
Labels: size/S

#240 adding spack test for e4s/23.08
  .gitlab-ci.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/amrex.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/arborx.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/bolt.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/caliper.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/dyninst.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/fortrilinos.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/ginkgo.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/hdf5.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/heffte.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/hpctoolkit.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/kokkos.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/legion.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/omega-h.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/openpmd-api.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/papi.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/papyrus.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/parsec.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/pumi.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/py-h5py.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/py-libensemble.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/py-petsc4py.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/qthreads.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/slate.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/slepc.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/strumpack.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/sundials.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/superlu.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/tasmanian.yml
  buildspecs/e4s/spack_test/perlmutter/23.08/tau.yml
  buildspecs/e4s/testgen/packages-spack_test-23.08-gcc.yaml
  buildspecs/e4s/testgen/spack-test-23.08-template.yaml
Labels: size/XL

#241 Remove e4s testsuite tests that run spack smoke tests.
  buildspecs/e4s/E4S-Testsuite/perlmutter/22.11/adios2.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/22.11/gasnet.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/22.11/superlu-dist.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/22.11/vtk-m.yml
  buildspecs/e4s/testgen/packages-spack_test-22.11-gcc.yaml
  buildspecs/e4s/testgen/packages-spack_test-23.05-gcc.yaml
  buildspecs/e4s/testgen/packages-spack_test-23.08-gcc.yaml
  buildspecs/e4s/testgen/packages.yaml
Labels: size/L

#242 Added test specs for e4s 23.05 and 23.08.
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/aml.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/amrex.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/arborx.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/bolt.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/caliper.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/fortrilinos.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/ginkgo.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/heffte.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/hpctoolkit.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/kokkos.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/legion.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/mfem.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/omega-h.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/openpmd-api.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/papyrus.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/parsec.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/pumi.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/py-h5py.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/py-libensemble.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/py-petsc4py.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/qthreads.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/slate.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/slepc.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/sundials.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/superlu.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/tasmanian.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.05/tau.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/amrex.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/arborx.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/bolt.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/caliper.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/dyninst.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/fortrilinos.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/ginkgo.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/hdf5.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/heffte.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/hpctoolkit.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/kokkos.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/legion.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/omega-h.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/openpmd-api.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/papi.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/papyrus.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/parsec.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/pumi.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/py-h5py.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/py-libensemble.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/py-petsc4py.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/qthreads.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/slate.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/slepc.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/strumpack.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/sundials.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/superlu.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/tasmanian.yml
  buildspecs/e4s/E4S-Testsuite/perlmutter/23.08/tau.yml
  buildspecs/e4s/testgen/e4s-23.05-template.yaml
  buildspecs/e4s/testgen/e4s-23.08-template.yaml
  buildspecs/e4s/testgen/packages-spack_test-23.05-gcc.yaml
  buildspecs/e4s/testgen/testgen.py
Labels: size/XXL
