Repository buildtesters/buildtest-nersc, pull requests merged in 2023-08, with the labels that each got.

#195 update spack directory checks test
  buildspecs/apps/spack/spack_directory_checks.yml
Labels: size/S

#196 regenerate all spack based tests for 22.11
  buildspecs/e4s/spack_test/perlmutter/22.11/aml.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/amrex.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/arborx.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/bolt.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/caliper.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/fortrilinos.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/gasnet.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/ginkgo.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/gptune.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/heffte.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/hpctoolkit.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/kokkos.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/legion.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/mfem.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/omega-h.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/openpmd-api.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/papyrus.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/parallel-netcdf.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/parsec.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/pumi.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/py-h5py.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/py-libensemble.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/py-petsc4py.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/py-warpx.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/qthreads.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/slate.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/slepc.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/sundials.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/superlu.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/tasmanian.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/tau.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/upcxx.yml
  buildspecs/e4s/spack_test/perlmutter/22.11/vtk-m.yml
  buildspecs/e4s/testgen/spack-test-22.11-template.yaml
Labels: size/M

#197 add timeout for 3600sec (1hr) for all jobs and disable rules condition
  .gitlab-ci.yml
Labels: size/S

#198 Remove cori slurm jobs and queue tests
  .archive/jobs/access_buffer.yml
  .archive/jobs/create_buffer.yml
  .archive/jobs/data_stage_burst_buffer.yml
  .archive/jobs/delete_buffer.yml
  .archive/jobs/fail/exit1.yml
  .archive/jobs/fail/flex_queue_time_limit.yml
  .archive/jobs/fail/interactive_queue.yml
  .archive/jobs/fail/max_nodes_haswell.yml
  .archive/jobs/fail/max_nodes_knl.yml
  .archive/jobs/fail/oom.yml
  .archive/jobs/fail/src/oom.c
  .archive/jobs/fail/submit_limit_test.yml
  .archive/jobs/fail/time_limit_queue.yml
  .archive/jobs/fail/timeout.yml
  .archive/jobs/metadata.yml
  buildspecs/jobs/affinity_check.yml
  buildspecs/jobs/gpuquery.yml
  buildspecs/jobs/submit_esslurm_from_compute.yml
  buildspecs/queues/bigmem.yml
  buildspecs/queues/compile.yml
  buildspecs/queues/hostname.yml
  buildspecs/queues/shared.yml
  buildspecs/queues/xfer.yml
Labels: size/L

#201 Fixed invalid buildspecs with executor cori
  .gitignore
  buildspecs/modules/e4s_moduletest.yml
  buildspecs/modules/module_sanity.yml
  buildspecs/modules/moduletest.yml
Labels: size/M

#202 remove invalid compilers from configuration file
  config.yml
Labels: size/S
